// 课程
export const CANCEL_COURSE = 'CANCEL_COURSE'
export const RECEIVE_ALL_COURSES = 'RECEIVE_ALL_COURSES'
// 试卷
export const RECEIVE_ALL_PAPER = 'RECEIVE_ALL_PAPER'
export const DELETE_PAPER = 'DELETE_PAPER'
export const MODIFY_PAPER = 'MODIFY_PAPER'
export const RECEIVE_UNEXIST_QUESTIONS = 'RECEIVE_UNEXIST_QUESTIONS'
export const RECEIVE_EXIST_QUESTIONS = 'RECEIVE_EXIST_QUESTIONS'
export const REMOVE_EXIST_QUESTION = 'REMOVE_EXIST_QUESTION'
export const ADD_QUESTION = 'ADD_QUESTION'
// 考题
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'