// 课程
export const CANCEL_COURSE = 'CANCEL_COURSE'
export const RECEIVE_ALL_COURSES = 'RECEIVE_ALL_COURSES'
// 试卷
export const RECEIVE_ALL_PAPER = 'RECEIVE_ALL_PAPER'
export const DELETE_PAPER = 'DELETE_PAPER'